### ISSUE TITLE
Solve Problem 2 in Scala

### ISSUE THREAD

**Issue by yafiwebdev** [yafiwebdev/ProjectEuler100#48]

**Comment by pabus** [comment]
@yafiwebdev I like to work on this. please assign this to me.

**Comment by yafiwebdev** [comment]
> @yafiwebdev I like to work on this. please assign this to me.

You asked for quite a few issues, I'll hold off assigning more to you until you're done with the ones on your plate.

Thank you for contributing

**Comment by lywc20** [comment]
@yafiwebdev I like to work on this. please assign this to me.

**Comment by yafiwebdev** [comment]
> @yafiwebdev I like to work on this. please assign this to me.

Have at it!
